baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Shardul Nalegave'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
description = "Systems & Networking Developer | Open-Source Enthusiast"

# Appearance settings
theme = 'dark'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hey There!'
homeIntroContent = """
I'm a Computer Engineering sophomore @ PICT in Pune, India.
I'm interested in a range of topics, including systems programming, computer networks, distributed computing and databases.
"""

# Collection to display on home
homeCollectionTitle = 'Projects'
homeCollection = 'projects'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/shardul-nalegave/"

[[params.social]]
name = "github"
url = "https://github.com/ShardulNalegave"

[[params.social]]
name = "x"
url = "https://x.com/ShardulNalegave"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
